name: CI

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node_version: ${{ matrix.node-version }}
      - name: Install root deps
        run: npm ci
      - name: Run basic tests
        run: |
          npm --workspace backend run test --if-present
          npm --workspace frontend run test --if-present